### ISSUE TITLE
unwanted resize

### ISSUE THREAD

**Issue by mmouterde** [mmouterde/FlexyTrello#22]
When I add card to list, the list width is resized ;o(

**Comment by JoelAzaria** [comment]
Same problem when dragging a card within a list.  List resizes and lose your place.

**Comment by mmouterde** [comment]
Yep... Thanks for reporting !
I'm working on another solution based on a "width stepper button" instead of the bugged "resize corner".

**Comment by JoelAzaria** [comment]
Ok, good effort.  It fixes the refresh issue when dragging cards or re-sizing columns, so that's good but I'm having an issue where when I increase the column size (say to 2 col) the list expands but not quite wide enough for two cols of cards so I have a two col wide list but just one col of cards in it.  It's probably short by just a few pixels but it's kinda weird.  Consequently if I hit increase again the list bumps to three wide and two cols of cards. If I go up to 4 cols it seems to catch up (parity) and reducing to 3 and 2 cols seems to stay matched (cols vs list width) so might be just a slight math glitch.

Either way, please have a look.  So far great work and it seems to be coming together so thanks for your efforts.

See screencap:
![clipboard01](https://cloud.githubusercontent.com/assets/470908/7816991/b819c200-039f-11e5-9cd8-4fab4887a00c.jpg)
