### ISSUE TITLE
Settings lost after changing board in trello

### ISSUE THREAD

**Issue by xko** [mmouterde/FlexyTrello#29]
..All lists are reset and extension buttons disappear. Buttons are back after reloading page, but settings lost..

**Comment by mmouterde** [comment]
hum, I can not reproduce the second part of this issue : On changing board, settings & buttons are not well initilized, but after reloading page, I get all my settings.

**Comment by xko** [comment]
@mmouterde,  looks like intermittent. I repeated the process 4-5 times - settings where back after reload. But then I lost them on all the boards at once (even the ones I didn't touch during my test)

**Comment by xko** [comment]
Chrome Version 57.0.2987.133 (64-bit), OSX Sierra

**Comment by maluhub** [comment]
Chrome 58.0.3029.110 (64-bit), Windows

After page reload my board columns revert to original state. Seems like FlexyTrello remembers settings, but does not apply them after reload, because you can do the following:
1. Make some trello column 2 columns wide using FlexyTrello expanding arrow in the bottom.
2. Reload page: this column becomes 1 column wide as in original
3. Press expanding arrow: this column becomes 3 colums wide immediately (switches from 1 to 3).

**Comment by mmouterde** [comment]
- please could you check (or reset) your authentication from Trello ? (using "Disable FlexyTrello to use your Trello account" in options of the extension)
- do you use the Pro version ?
- are you using public board ?
- do you use other trello chrome extensions ?

**Comment by maluhub** [comment]
@mmouterde thanks! Enabling authentication helped, I didn't know it was disabled - probably after my computer failure and restoration.
