### ISSUE TITLE
Make Resize lists persistent

### ISSUE THREAD

**Issue by ghost** [mmouterde/FlexyTrello#9]
... so that i can "save" my lists configuration.

**Comment by mmouterde** [comment]
Exact.

Trello is not friendly for that. The DOM does not provide list IDs, so I need to access Trello REST API to be able to identify lists order...

**Comment by ghost** [comment]
Please go ahead. It is thanks to FlexyTrello if we can imagine a new concept for trello. 
Do you like it? ;) https://www.uploady.com/#!/download/qawtf9UoG5z/rObIuhY8Rlz5EDZl

**Comment by mmouterde** [comment]
Do you ever try https://chrome.google.com/webstore/detail/vertical-lists-for-trello/aldklnbenbdgfgfbflalmlddkkndgnlc?hl=fr ?

**Comment by ghost** [comment]
Yes! That board works with Vertical list for trello + Flexy Trello. Great! :). 
That's why persistent lists/lanes size is so important.

**Comment by mmouterde** [comment]
blocked by Chrome issue : https://code.google.com/p/chromium/issues/detail?id=94583
Looking for workaround ...

**Comment by JoelAzaria** [comment]
Any further news on this issue?

**Comment by mmouterde** [comment]
No news on the Chrome issue :(
I tried several technical (css&js) workarounds but without result.

Anyway, I will make a functionnal workaround in the next release : a "reset size" button...

Is someone has a better idea..

**Comment by mmouterde** [comment]
I found workaround. Someone to test before publishing ?

**Comment by mmouterde** [comment]
fixed in 1.2.0

**Comment by tomgiorgio** [comment]
I am on 1.2.1 and list resizing is not persistent after a page refresh.

**Comment by mmouterde** [comment]
Did you configure the extension on its options pages ?
It is required to allow this extension to access to Trello to make persitence working.

**Comment by tomgiorgio** [comment]
Nope, didn't realize there were options now. Thanks!

**Comment by JoelAzaria** [comment]
Am on 1.2.2 and persistence works.  Very nice.

There is a slight glitch, can't exactly figure it out yet - 
I have a list (Today) with 14 cards in it.  I make that list 4 cards wide.
Then the next list to the right (This Week) with 25 cards in it.  If I make the list wider it's fine.  But then if I try to REadjust the width of the This Week list, there's a weird glitch that sort of "resets" the width of the This Week list - it collapses to 1 card wide and then let's you expand again.
It almost looks like there's a refresh of something (the list maybe?) at the moment I grab the resize handle which is screwing it up.

The use-case problem is that I widen both of these columns. When I widen the second list (This Week) my cursor reaches the right edge of the screen so I have to stop and manually scroll the Trello window.  Then when I grab the resize handle to widen further (say from 4 columns to 6), it does this refresh thing and moves the trello window so I can never get to 6 columns. I can only do it if I'm on my desktop rig w/ 2 monitors and put trello on my left monitor (so I can drag my mouse past the trello window edge through my right monitor)  

I may resize the This Week list a couple of times a day.  With persistence fixed I can ride it out a bit but would be great if you can fix the glitch.

Otherwise great work dude.  This extension is definitely a big plus for Trello for me so thank you.

----EDIT
Just to add - If I collapse (minimize) the Today list the glitch doesnt happen so I thiknit's related to the fact that there's a wide list to the left of the list I'm widening (This Week).  For the record Today is list position 3 on the board and This Week is position 4.
hth.

**Comment by mmouterde** [comment]
Ok, I created an issue #21.
Could you tell me is this matches with the glitch you met ?
